### ISSUE TITLE
Finishing Checklist

### ISSUE THREAD

**Issue by bluelotus03** [bluelotus03/Hackcoming-Game-2021#21]
- [x] Complete Devpost submission 
   - [x] Upload thumbnail 
   - [x] Upload demo
   - [x] Upload media
   - [x] Complete TODOs 
- [x] Create a new release for version 2.0.0
- [x] Check all game details and update notes for accuracy of functionality implemented this round
